### ISSUE TITLE
可以移植到openwrt上用吗?

### ISSUE THREAD

**Issue by jiasai007** [edwardvon/uuplugin-redmi-ax6000#1]
可以移植到openwrt上用吗?官方发布的 找不到PC

**Comment by edwardvon** [comment]
你好，openwrt可以参考uu官方指引 https://router.uu.163.com/app/html/online/baike_share.html?baike_id=5f963c9304c215e129ca40e8

理论上也是先有openwrt再有的米路由插件。

**Comment by edwardvon** [comment]
我误会你的问题了，我自己用的时候可以看到pc。
印象中之前用openwrt版本时也能看到pc，官方插件有个配置文件是显示设备类型的参数，也可以留意一下。

**Comment by jiasai007** [comment]
首先感谢回复, 官方发布的openwrt上的UU插件 是不支持PC加速的 只能加速游戏机,
只有官方发布的UU盒子或者合作的华为小米等路由器 才可以加速 手机及PC 
如果您的移植版可以在openwrt中使用 那真是造福大家了 希望您能解决

**Comment by edwardvon** [comment]
我误会你的问题了，我自己用的时候可以看到pc。
印象中之前用openwrt版本时也能看到pc，官方插件有个配置文件是显示设备类型的参数，也可以留意一下。
![Uploading Screenshot_2023-06-28-22-21-53-320_com.netease.uurouter-edit.jpg…]()

**Comment by edwardvon** [comment]
我误会你的问题了，我自己用的时候可以看到pc。
印象中之前用openwrt版本时也能看到pc，官方插件有个配置文件是显示设备类型的参数，也可以留意一下。
![Screenshot_2023-06-28-22-21-53-320_com netease uurouter-edit](https://github.com/edwardvon/uuplugin-redmi-ax6000/assets/16309465/92486e70-a13a-49cf-9d51-551fc75557ed)

**Comment by edwardvon** [comment]
> 首先感谢回复, 官方发布的openwrt上的UU插件 是不支持PC加速的 只能加速游戏机, 只有官方发布的UU盒子或者合作的华为小米等路由器 才可以加速 手机及PC 如果您的移植版可以在openwrt中使用 那真是造福大家了 希望您能解决

我手边没有纯官方openwrt设备可以测试。我会抽空看看官版拆件的配置文件

**Comment by jiasai007** [comment]
你用的这个是红米ax6000的路由器吧,路由器是可以的,
NGA上有人问过UU的技术 说是openwrt不支持PC 
辛苦了,代表广大玩家 再次感觉您的付出

**Comment by edwardvon** [comment]
> 首先感谢回复, 官方发布的openwrt上的UU插件 是不支持PC加速的 只能加速游戏机, 只有官方发布的UU盒子或者合作的华为小米等路由器 才可以加速 手机及PC 如果您的移植版可以在openwrt中使用 那真是造福大家了 希望您能解决

建议你把这个库里的文件夹扔openwrt里，运行里面的uuplugin_monitor.sh测试一下，理论上是可以直接用的

**Comment by jiasai007** [comment]
我运行了下报uuplugin: line 1: syntax error: unexpected  
我用的是x86的openwrt 不支持Arm的程序 哎~

**Comment by edwardvon** [comment]
> 你用的这个是红米ax6000的路由器吧,路由器是可以的, NGA上有人问过UU的技术 说是openwrt不支持PC 辛苦了,代表广大玩家 再次感觉您的付出

@jiasai007 我刚测试了下，确实官方原版不显示pc。但是我看了下官方的安装脚本，实际上核心就uuplugin二进制文件和uuplugin_monitor.sh。
这里面同架构的二进制文件理论上可以互换运行，例如红米ax6000是aarch64。
