### ISSUE TITLE
自动执行脚本似乎无效

### ISSUE THREAD

**Issue by pth2000** [edwardvon/uuplugin-redmi-ax6000#2]
uu的脚本似乎是阻塞的，手动执行不释放命令行，重启路由器后在app中提示无网络连接。

**Comment by edwardvon** [comment]
echo "sleep 5 && /bin/sh /data/uuplugin/auto.sh &" >> /data/auto_ssh/auto_ssh.sh

**Comment by pth2000** [comment]
> echo "sleep 5 && /bin/sh /data/uuplugin/auto.sh &" >> /data/auto_ssh/auto_ssh.sh

该命令会将此语句直接拼接至sh文件的`main "$@"`后面，导致执行出现问题。目前已经正常运行，感谢
