### ISSUE TITLE
我的ax6000好像sftp连接不了怎么弄

### ISSUE THREAD

**Issue by mikumifa** [edwardvon/uuplugin-redmi-ax6000#4]
如题

**Comment by mikumifa** [comment]
![image](https://github.com/edwardvon/uuplugin-redmi-ax6000/assets/99951454/fffeced1-9306-41fa-9345-4385050f5b0b)

**Comment by edwardvon** [comment]
官方固件吗？解锁ssh了吗？（官方固件先解锁SSH，详请见：https://www.right.com.cn/forum/thread-8258466-1-1.html ）

**Comment by mikumifa** [comment]
感谢回复，好了，解决了，我用scp传文件了



---原始邮件---
发件人: "Edward ***@***.***&gt;
发送时间: 2024年1月17日(周三) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [edwardvon/uuplugin-redmi-ax6000] 我的ax6000好像sftp连接不了怎么弄 (Issue #4)




 
官方固件吗？解锁ssh了吗？（官方固件先解锁SSH，详请见：https://www.right.com.cn/forum/thread-8258466-1-1.html ）

**Comment by edwardvon** [comment]
🆗
