### ISSUE TITLE
无法绑定插件

### ISSUE THREAD

**Issue by Skyblockrh** [edwardvon/uuplugin-redmi-ax6000#6]
运行环境：
OpenWrt 23.0.5
架构：
aarch64
设备：
H3C NX30 PRO

运行步骤：
1.下载项目全部文件
2,export LD_LIBRARY_PATH=libssl的文件位置
3.安装iptables组件和libcpp组件
4.直接运行uuplugin uu.conf

效果：
UU的APP能扫描到路由器，但是如果尝试绑定就提示绑定失败。。。可惜了
虽然修复的可能不大，还是希望开发大大能考虑解决一下，感谢大大的付出
![Screenshot_2024-01-28-19-20-53-107_com netease uurouter](https://github.com/edwardvon/uuplugin-redmi-ax6000/assets/33181526/5080e7d6-a48b-48de-9d59-0724f676bd8c)
![Screenshot_2024-01-28-19-20-56-315_com netease uurouter](https://github.com/edwardvon/uuplugin-redmi-ax6000/assets/33181526/b8337d21-5df1-497a-9491-ed8043299db3)

**Comment by edwardvon** [comment]
因为手上没有空余设备所以暂时没办法测，我会最近搞一台openwrt设备测试，

**Comment by edwardvon** [comment]
> 今天测试，把我的NX30PRO换成了官方固件，提取出来的UU再替换到OpenWRT上面，有两个发现 1、在绑定的时候，必须使用原来软件安装的目录才行，否则就无法绑定，APP上的区别是非特定目录只显示H3C，特定目录会显示具体型号，如NX30PRO，绑定完成后，如果仅运行，则是可以使用非特定目录的 2、在使用的时候（UU运行在OpenWRT上），只有网络中官方固件的上网模式为DHCP，并且设备连接到官方固件的路由器，才能识别到，如果设置为AP，连接主路由，并在OpenWrt主路由上运行UU，实际上是无法识别到设备的。猜测是OpenWrt屏蔽或者隔离了某些信息，导致APP无法识别

2是当然的，ap模式下路由器只做转发，不做路由功能

**Comment by edwardvon** [comment]
> 我改了一下h3cinfo里面的参数，之前的MAC地址写错了，复制的时候忘了修改所以出现了之前那个，奇葩问题，现在能够识别到设备了，但是加速会提示路由器系统网络组件初始化失败，我安装和删除了kmod-tun，都是初始化失败，不知道问题在哪，如果有新的发现，我会继续更新。

我其实还有个疑问，你openwrt装UU官方的版本能不能正常启动？ http://uu.gdl.netease.com/uuplugin-script/202012111056/install.sh
